# Site settings
title: "[ARCHIVE] CC†"
email: mail.cccroix@lgdubois.fr
description: > # this means to ignore newlines until "baseurl:"
    [ARCHIVE] La Communauté Chrétienne de CentraleSupélec à Metz
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://cccroix.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: cccroix
github_repo: cccroix.github.io
paginate: 10
paginate_path: "/page:num/"

default_text: |
    ---
    layout: post
    title: Mon titre
    author: monalias
    date: AAAA-MM-JJ hh:mm:ss CET
    categories: nouvelles
    ---

    # Mon sous-titre

    Mon texte.

collections:
 eglises:
   output: true

# Build settings
markdown: kramdown

sass:
    style: compressed

plugins:
    - jekyll-redirect-from
    - jekyll-paginate
